#
# The Short URL User Service
# (Copyright 2024 by Richard Klein)
#
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Short URL User Service - api.richarddklein.com/shorturl/users
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  # Define the Lambda function
  ShortUrlUserService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.richarddklein.shorturluserservice.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Timeout: 90
      Role: !GetAtt LambdaExecutionRole.Arn
      SnapStart:
        ApplyOn: "PublishedVersions"

      # Defined below are the REST endpoints. For each endpoint, a pair of
      # paths are defined. One path is for the case where the URL specifies
      # either the API Gateway or localhost. The other path is for the case
      # where the URL specifies the custom domain that redirects to the API
      # Gateway. Thus, an endpoint URL can have one of three possible values:
      #
      # API Gateway:   <aws-api-ID>.execute-api.us-east-2.amazonaws.com/Prod/shorturl/users/<endpoint>
      # localhost:     localhost:6000/shorturl/users/<endpoint>
      # Custom Domain: api.richarddklein.com/shorturl/users/<endpoint>
      #
      # When the service is running on your local machine, via the command
      # `sam local start-api`, use the above `localhost` URL.
      #
      # When the service is running on AWS, use either the above `API Gateway`
      # URL or the above `Custom Domain` URL. (It is recommended that you use
      # the `Custom Domain` hostname, as it is simpler to remember and to type.)
      #
      # For a description of the functionality provided by the REST endpoints,
      # see the comments in the `ShortUrlUserController` interface.
      Events:
        InitializeShortUrlUserTableViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/users/dbinit
            Method: POST
        InitializeShortUrlUserTableViaCustomDomain:
          Type: Api
          Properties:
            Path: /dbinit
            Method: POST
        GetAdminJwtTokenViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/users/adminjwt
            Method: GET
        GetAdminJwtTokenViaCustomDomain:
          Type: Api
          Properties:
            Path: /adminjwt
            Method: GET
        GetAllUsersViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/users/all
            Method: GET
        GetAllUsersViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: GET
        SignupViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/users/signup
            Method: POST
        SignupViaCustomDomain:
          Type: Api
          Properties:
            Path: /signup
            Method: POST
        LoginViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/users/login
            Method: POST
        LoginViaCustomDomain:
          Type: Api
          Properties:
            Path: /login
            Method: POST
        GetUserDetailsViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/users/details
            Method: GET
        GetUserDetailsViaCustomDomain:
          Type: Api
          Properties:
            Path: /details
            Method: GET
        ChangePasswordViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/users/changepassword
            Method: PATCH
        ChangePasswordViaCustomDomain:
          Type: Api
          Properties:
            Path: /changepassword
            Method: PATCH
        DeleteUserViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/users/specific
            Method: DELETE
        DeleteUserViaCustomDomain:
          Type: Api
          Properties:
            Path: /specific
            Method: DELETE
        DeleteAllUsersViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/users/all
            Method: DELETE
        DeleteAllUsersViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: DELETE

  # Define the IAM Role for the Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Write permission for CloudWatch logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              # Read/write permission for DynamoDB
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource: "*"
              # Custom read/write policy for SSM parameter `adminPassword`
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:PutParameter
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/shortUrl/users/adminPassword
              # Read policy for other SSM parameters
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/shortUrl/users/tableName
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/shortUrl/users/adminUsername
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/shortUrl/users/jwtMinutesToLive
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/shortUrl/users/jwtSecretKey
